// write a function that generates a random integer 1 - 12

var month = Math.ceil(Math.random() * 12)

// write a function that outputs a string on the name of the
// month generated by your random number

// ex: 3 -> "March"

var monthName;
switch (month) {
    case 1:
        monthName = "January";
        break;
    case 2:
        monthName = "February";
        break;
    case 3:
        monthName = "March";
        break;
    case 4:
        monthName = "April";
        break;
    case 5:
        monthName = "May";
        break;
    case 6:
        monthName = "June";
        break;
    case 7:
        monthName = "July";
        break;
    case 8:
        monthName = "August";
        break;
    case 9:
        monthName = "September";
        break;
    case 10:
        monthName = "October";
        break;
    case 11:
        monthName = "November";
        break;
    case 12:
        monthName = "December";
        break;
    default:
        break;
}

console.log(monthName);

switch (month) {
    case 9:
    case 4:
    case 6:
    case 11:
        numDays = 30;
        break;
    case 2:
        numDays = 29;
        break;
    default:
        numDays = 31;
        break;
}

console.log(monthName + " has " + numDays + " days.")


// if (a === 1) {
//     console.log("a is 1")
// } else if (a == 2) {
//     console.log("a is 2")
// } else if (a == 3) {
//     console.log("a is 3")
// } else {
//     console.log("a is not 1, 2, or 3")
// }
var a = 4;

switch (a) {
    case 1:
        console.log("a is 1")
        break;
    case 2:
        console.log("a is 2")
        break;
    case 3:
        console.log("a is 3")
        break;
    default:
        console.log("a is not 1, 2, or 3")
}